import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import { useTransition, config, animated } from "react-spring";

import Keyboard from "../components/Keyboard";

const Home: NextPage = () => {
    const mount = true;

    const transitions = useTransition(mount, {
        from: { opacity: 0 },
        enter: { opacity: 1 },
        leave: { opacity: 0 },
        delay: 1000,
        config: config.slow,
    });

    return (
        <div className={styles.container} data-test="comp-home">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {transitions((styles, item) =>
                    item ? <Test style={styles}>NOTHING</Test> : null
                )}

                <Keyboard data-test="comp-keyboard" />
                <div data-test="comp-fav" />
            </main>
        </div>
    );
};

export default Home;

const Test = styled(animated.div)`
    background-color: red;
    color: white;
`;
